# Generated by Django 5.2.15 on 2026-06-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField(help_text='Kilometraje en KM')),
                ('color', models.CharField(max_length=30)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'CVT'), ('Dual-Clutch', 'Dual_Clutch')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasolina'), ('Diesel', 'Diesel'), ('Electric', 'Eletrico'), ('Hybrid', 'Hibrido')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-created_at'],
            },
        ),
    ]
